//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.UserInfoes = new HashSet<UserInfo>();
        }
    
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string ApiKey { get; set; }
    
        public virtual ICollection<UserInfo> UserInfoes { get; set; }
    }
}
